CREATE DATABASE projeto_tomate;
USE projeto_tomate;

CREATE TABLE cadastro_empresa (
idCadastro INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(30) NOT NULL,
sobrenome VARCHAR(255) NOT NULL,
dtNasc DATE NOT NULL,
cnpj CHAR(20) NOT NULL,
ddd VARCHAR(10) NOT NULL,
telefone VARCHAR(30) NOT NULL,
email VARCHAR(190) NOT NULL,
cep CHAR(10) NOT NULL,
uf CHAR(2) NOT NULL,
cidade VARCHAR(100) NOT NULL,
bairro VARCHAR(100) NOT NULL,
numero VARCHAR(30) NOT NULL,
complemento VARCHAR(190) NOT NULL
);

-- CRIAR A TABELA DE CAPTURA DE DADOS DO ARDUINO

CREATE TABLE arduino (
idArduino INT PRIMARY KEY,
localizacao VARCHAR(255) NOT NULL,
luzmax INT NOT NULL,
alerta TEXT,
dtAlerta DATETIME DEFAULT current_timestamp
);

--  CRIAR A TABELA DE PRODUTOS TOMATES
CREATE TABLE tomate (
idTomate INT PRIMARY KEY,
tipo VARCHAR(100) NOT NULL,
luzMin INT NOT NULL,
luzMax INT NOT NULL
);